# Generated by Django 4.1.6 on 2023-02-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="author",
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
